---
title: "Testing"
author: "Justin L"
date: "4/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
library(aiR)
#library(foreach)
# library(gapminder)
# library(gganimate)
# library(animation)
```

```{r}
#Training data 1

set.seed(6227)
group1.x <- runif(n = 4200)
group1.y <- runif(n = 4200)
group2.x <- runif(n = 4200, min = -1, max = .5)
group2.y <- runif(n = 4200, min = -1, max = .1)

g1 <- cbind(group1.x,group1.y, rep("g1",4200))
colnames(g1) <- c("x","y","group")
g2 <- cbind(group2.x,group2.y, rep("g2",4200))
colnames(g2) <- c("x","y","group")

train <- as.data.frame(rbind(g1,g2))
train <- justinmisc::correct.mode(train,c("num","num","Factor"))
#train$z <- runif(300)
ggplot(train, aes(x,y, color = group)) +
  geom_point()

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}

mylayers <- aiRnet(c(2,4,4,2))
# layer1 <- aiRlayer(2,4)
# layer2 <- aiRlayer(4,2)
# mylayers <- list(layer1, layer2)

# train <- rbind(train, data.frame(x = c(.7, .9, .6, -.7,-.9,-.6),
#                         y = c(-.7,-.6,-.9, .5, .3, .8),
#                         group = c("g2","g2","g2","g1","g1","g1"),
#                         z = c(.1,.2,.4,.5,.7,-.8)))

set.seed(778)
obj <- aiR(data = train,
           input.col = c("x","y"),
                   var.classify = "group",
                   aiRnet = mylayers,
                   cycles = 200,
                   batch.size = 30,  test.rate = 5)

```

```{r}
plot(obj$aiRnet, layers = NULL)
```


```{r}
dat <- na.exclude(gather(obj$Cost, key = "cost.type", value = "cost.value", -cycles))
ggplot(data = dat, aes(x = cycles, y = cost.value, color = cost.type)) +geom_point() + scale_y_log10()
```


```{r}
new <- aiRactivation(data = train[,c("x","y")], aiRnet = obj$aiRnet)
classify_obj <- aiRclassify(data = train[,c("x","y")], factor = levels(train$group), aiRnet = obj$aiRnet)

ggplot(train, aes(x = x, y = y)) +
  geom_point(aes(color = as.factor(classify_obj$classify), alpha = classify_obj$node.max)) 
```

```{r}
aiRrate(data = train, factor = "group", aiRnet = obj$aiRnet)
```

```{r}
# inverseSigmoid <- function(x){
#   x <- scales::rescale(x, to = c(0.000000001, 0.9999999999))
#   log(x/(1-x))
# }

```


```{r}

plot(aiRactivation = new, x.val = "x", y.val = "y", layer = "layer1")
plot(new, x.val = "x", y.val = "y", layer = "layer2")
plot(aiRactivation = new, x.val = "x", y.val = "y", layer = "layer3")
```


```{r}

```

